global using Ardalis.Specification.EntityFrameworkCore;
global using Immediate.Apis.Shared;
global using Immediate.Handlers.Shared;
global using Immediate.Validations.Shared;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using System.Net;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Taskly.Shared.WebApi.Responses.Todos;
global using Taskly.WebApi.Common.Infrastructure.Persistence;
global using Taskly.WebApi.Common.Shared;
global using Taskly.WebApi.Common.Shared.Exceptions;
global using Taskly.WebApi.Features.Tags.Common.Models;
global using Taskly.WebApi.Features.Todos.Common.Models;
global using Taskly.WebApi.Features.Users.Common.Services;
global using Vogen;
global using Attachment = Taskly.WebApi.Features.Attachments.Common.Models.Attachment;
global using TodoId = Taskly.WebApi.Features.Todos.Common.Models.TodoId;